# Generated by Django 5.2.16 on 2026-07-09 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('battery_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='accounts.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to='attendance.session')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['employee', 'timestamp'], name='tracking_lo_employe_4450cb_idx'), models.Index(fields=['session', 'timestamp'], name='tracking_lo_session_3dd3f0_idx')],
            },
        ),
    ]
