# Generated by Django 5.2.16 on 2026-07-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_activitylog_notification_patientvisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='photo_public_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='photo_public_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
