# Generated by Django 5.2.16 on 2026-09-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_photo_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected')], default='GENERAL', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
