# Generated by Django 5.2.16 on 2026-09-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_devicepushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicepushtoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
