# Generated by Django 5.2.16 on 2026-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
