# Generated by Django 5.2.16 on 2026-09-10 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_shift_end_time_employee_shift_name_and_more'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='accounts.employee')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='communication.message')),
            ],
            options={
                'unique_together': {('message', 'employee', 'emoji')},
            },
        ),
    ]
