# Generated by Django 5.2.16 on 2026-09-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_shift_end_time_employee_shift_name_and_more'),
        ('communication', '0002_conversation_group_name_messagereaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'employee')},
        ),
    ]
