# Generated by Django 5.2.16 on 2026-09-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_employee_shift_end_time_employee_shift_name_and_more'),
        ('communication', '0003_alter_messagereaction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='group_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
