# Generated by Django 5.2.16 on 2026-07-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin')], default='ADMIN', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeviceBinding',
        ),
    ]
