# Generated by Django 5.2.16 on 2026-07-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_device_id_employee_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_radius',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
