# Generated by Django 5.2.16 on 2026-07-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employee_default_address_employee_default_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_photo_public_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
