# Generated by Django 5.2.16 on 2026-07-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_employee_profile_photo_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift_end_time',
            field=models.TimeField(default='18:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_name',
            field=models.CharField(default='General Shift', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_off_days',
            field=models.CharField(default='Sunday', help_text='Comma separated off days e.g. Sunday or Monday,Sunday', max_length=120),
        ),
    ]
