# Generated by Django 5.2.16 on 2026-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('MATERNITY_PATERNITY', 'Maternity / Paternity Leave'), ('BEREAVEMENT', 'Bereavement Leave'), ('UNPAID', 'Unpaid Leave')], default='CASUAL', max_length=30),
        ),
    ]
