# Generated by Django 5.2.16 on 2026-07-29 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('REGULAR', 'Generate Invoice (Regular)'), ('SCHOOL', 'Generate Invoice (School / College)'), ('MULTI_SERVICE', 'Generate Invoice (Multi-Service)')], default='REGULAR', max_length=30)),
                ('barcode_value', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('billing_period_text', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_contact', models.CharField(blank=True, max_length=50)),
                ('client_address', models.TextField(blank=True)),
                ('client_gst', models.CharField(blank=True, max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=200)),
                ('patient_age_gender', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(blank=True, max_length=200)),
                ('consultant', models.CharField(blank=True, max_length=200)),
                ('service_start_date', models.DateField(blank=True, null=True)),
                ('service_end_date', models.DateField(blank=True, null=True)),
                ('rendered_days', models.CharField(blank=True, max_length=100)),
                ('school_branch', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_person_designation', models.CharField(blank=True, max_length=200)),
                ('no_of_nurses', models.IntegerField(default=0)),
                ('no_of_students', models.IntegerField(default=0)),
                ('per_day_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_after_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=300)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Not Paid'), ('PARTIAL', 'Partial / Advance Received'), ('PENDING', 'Pending')], default='UNPAID', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('services_data', models.JSONField(blank=True, default=list)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.CharField(default='HR Admin', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='1370', max_length=20)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
