# Generated by Django 5.2.16 on 2026-07-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='display_hash',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='verification_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
