# Generated by Django 5.2.16 on 2026-08-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_display_hash_invoice_verification_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoicecounter',
            name='prefix',
            field=models.CharField(default='1369', max_length=20),
        ),
    ]
