# Generated by Django 5.2.16 on 2026-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_gst_rate_alter_invoicecounter_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_end_date',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_start_date',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
