# Generated by Django 5.2.16 on 2026-09-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='age',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
