# Generated by Django 5.2.16 on 2026-09-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_age_invoice_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_gstin',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
