from django.urls import path

from apps.communication.views import (
    CommunicationOverviewView,
    ConversationListCreateView,
    ConversationMessageListView,
    ConversationReadView,
    EmployeeSearchView,
    MessageDeleteView,
    PresenceHeartbeatView,
    TypingStatusView,
    UnreadCountView,
    MessageReactionView,
    GroupListCreateView,
    GroupDetailView,
    AdminEmployeeConversationsView,
    AdminConversationMessagesView,
    ConversationPresenceView,
)

urlpatterns = [
    path("employees/search/", EmployeeSearchView.as_view(), name="communication-employee-search"),
    path("employees/search", EmployeeSearchView.as_view()),
    path("conversations/", ConversationListCreateView.as_view(), name="communication-conversations-list-create"),
    path("conversations", ConversationListCreateView.as_view()),
    path("conversations/<int:conversation_id>/messages/", ConversationMessageListView.as_view(), name="communication-conversation-messages"),
    path("conversations/<int:conversation_id>/messages", ConversationMessageListView.as_view()),
    path("conversations/<int:conversation_id>/read/", ConversationReadView.as_view(), name="communication-conversation-read"),
    path("conversations/<int:conversation_id>/read", ConversationReadView.as_view()),
    path("conversations/<int:conversation_id>/presence/", ConversationPresenceView.as_view(), name="communication-conversation-presence"),
    path("conversations/<int:conversation_id>/presence", ConversationPresenceView.as_view()),
    path("conversations/<int:conversation_id>/typing/", TypingStatusView.as_view(), name="communication-conversation-typing"),
    path("conversations/<int:conversation_id>/typing", TypingStatusView.as_view()),
    path("messages/<int:message_id>/", MessageDeleteView.as_view(), name="communication-message-delete"),
    path("messages/<int:message_id>/reactions/", MessageReactionView.as_view(), name="communication-message-reactions"),
    path("groups/", GroupListCreateView.as_view(), name="communication-groups-list-create"),
    path("groups", GroupListCreateView.as_view()),
    path("groups/<int:group_id>/", GroupDetailView.as_view(), name="communication-group-detail"),
    path("groups/<int:group_id>", GroupDetailView.as_view()),
    # Admin-only inspection routes
    path("admin/employees/<int:employee_id>/conversations/", AdminEmployeeConversationsView.as_view(), name="communication-admin-employee-conversations"),
    path("admin/employees/<int:employee_id>/conversations", AdminEmployeeConversationsView.as_view()),
    path("admin/conversations/<int:conversation_id>/messages/", AdminConversationMessagesView.as_view(), name="communication-admin-conversation-messages"),
    path("admin/conversations/<int:conversation_id>/messages", AdminConversationMessagesView.as_view()),
    path("presence/ping/", PresenceHeartbeatView.as_view(), name="communication-presence-ping"),
    path("unread-count/", UnreadCountView.as_view(), name="communication-unread-count"),
    path("overview/", CommunicationOverviewView.as_view(), name="communication-overview"),
]
