# Generated by Django 5.2.16 on 2026-08-25 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_employee_shift_end_time_employee_shift_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('month', models.CharField(max_length=32)),
                ('year', models.IntegerField(default=2026)),
                ('generation_date', models.CharField(blank=True, max_length=32)),
                ('generation_time', models.CharField(blank=True, max_length=32)),
                ('employee_code', models.CharField(db_index=True, max_length=64)),
                ('employee_name', models.CharField(db_index=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('grade_level', models.CharField(default='AA / II', max_length=64)),
                ('location', models.CharField(default='TELANGANA', max_length=255)),
                ('department', models.CharField(default='OPERATIONS', max_length=255)),
                ('bank_name', models.CharField(default='SBI', max_length=128)),
                ('bank_account_number', models.CharField(blank=True, max_length=128)),
                ('pan_number', models.CharField(default='NA', max_length=64)),
                ('pf_account_number', models.CharField(default='NA', max_length=64)),
                ('date_of_joining', models.CharField(blank=True, max_length=64)),
                ('days_worked', models.IntegerField(default=30)),
                ('lop_days', models.IntegerField(default=0)),
                ('arrears_days', models.IntegerField(default=0)),
                ('esic_account_number', models.CharField(default='NA', max_length=64)),
                ('uan_number', models.CharField(default='NA', max_length=64)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('conveyance_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('others_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('incentives', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('esic_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tds_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_in_words', models.TextField(blank=True)),
                ('cloudinary_pdf_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='accounts.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
